version: '3'
services:
  front-end:
    build:
      context: ./front-end
    image: task6_front-end
    depends_on:
      - back-end
    expose:
      - "9000"
  
  back-end:
    build:
      context: ./back-end
    image: task6_back-end
    expose:
      - "5252"
    deploy:
      replicas: 2  # This line scales the API server to two replicas
  
  proxy:
    build:
      context: ./proxy
    image: task6_proxy
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
